### PR TITLE
Add Dripcap

### PR DESCRIPTION
**Pull request by h2so5**
https://github.com/dripcap/dripcap

### CODE REVIEW

**Comment by kazzkiq** [comment]
[Successfully published](http://riotjs.com/made-with-riot/). 👍

**Comment by rsbondi** [comment]
I got a trojan error from windows defender

https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fMefurac.E!cl&threatid=2147712355&enterprise=0

**Comment by kazzkiq** [comment]
I don't have a Windows machine so I can't verify this security issue. However, until further investigation and due to security concerns, I'm removing the project from production page.

**Comment by rsbondi** [comment]
[related discussion](https://github.com/ethereum/go-ethereum/issues/3527#issuecomment-271245664)

**Comment by cognitom** [comment]
I think it's a kind of *false positives* cases. At least this application seems working perfectly on Mac.
@h2so5 do you know any workarounds or suggestions?

Anyway thank you for your PR! And your presentation at the Riot meetup in Tokyo was really cool 😉

**Comment by kazzkiq** [comment]
I've tested the app on Windows and got no malware accusations whatsoever (Avast). VirusTotal returned "only" [4 warnings](https://virustotal.com/en/file/7dea931693597207252f9d93e48bfd83044164a5a41d7a3c6a303c56beb5b5a5/analysis/), all based on Chinese antivirus (never heard of any of them, not sure if they're trustful). All other (well-known) antivirus accused nothing.

Based on the evidences I'm inclined to believe its indeed just a *false positive*.

@h2so5 Would you like to add anything? This *false-positive* issue happened before?

@GianlucaGuarini is it ok to publish the project on the showcase then?

**Comment by h2so5** [comment]
I have not seen such warnings on windows but it is likely that some security softwares make doubt because Dripcap is a kind of packet sniffer.
Unlike all the other apps in the Riot.js showcase, Dripcap is an unsandboxed tool for the super-users and potentially insecure.

Besides, the windows installer doesn't have a code signature. (the macOS app binary does) 
I'm going to consider the code signing on windows in the future production releases.
https://github.com/electron/windows-installer#sign-your-installer-or-else-bad-things-will-happen

Anyway, I don't mind withdrawing this commit due to the security issue.

**Comment by kazzkiq** [comment]
I've tested Dripcap on my machine for a week now and could't find any kind of "malware" related issues. Also, the project is [open-source](https://github.com/dripcap/dripcap), [well documented](https://docs.dripcap.org/) and there were related issues about *false-positives* on other electron projects.

I will be adding it to the showcase.

**Pull request merged**
