### PR TITLE
Add Sociocaster.com

### PR DESCRIPTION
**Pull request by ydatech**
Sociocaster is the easiest way to build your business by using social media.

### CODE REVIEW

**Comment by kazzkiq** [comment]
@prateekbh To add the project to gh-pages you must:

- Clone the project
- Run
````
gulp compile:all
gulp deploy
```

**Comment by ydatech** [comment]
@prateekbh @kazzkiq  When does my project appear on Showcase Site (http://riotjs.com/made-with-riot/) ?

**Comment by kazzkiq** [comment]
@ydatech Its live! http://riotjs.com/made-with-riot/ 😉

**Comment by ydatech** [comment]
@kazzkiq thank you..

**Pull request merged**
