### PR TITLE
adding Honda

### PR DESCRIPTION
**Pull request by teolitto**
adding Honda :)

### CODE REVIEW

**Comment by cognitom** [comment]
Wow, cool!! 😲 

@teolitto I've got some error on the page on my console. Is that ok? (Chrome latest / macOS Sierra)
http://automobiles.honda.com/pilot#build-price

If not related to Riot, I don't mind. Thanks.

**Comment by prateekbh** [comment]
@cognitom @teolitto so awesome to see more PRs to this <3

**Comment by prateekbh** [comment]
@cognitom something went wrong while trying to merge this pull request, can you please check?
i ran the usual scripts

**Comment by prateekbh** [comment]
fixed and deployed 😆 
sorry for the trouble.
:)

**Comment by teolitto** [comment]
@cognitom Errors likely not related to Riot - there's a ton of stuff on that page, and there have always been issues with some of the analytics libraries etc. Can't vouch for what's happened since I left the project, but Riot was error free last I was on the project (10 mos or so ago) - I think it should be good.

@prateekbh @cognitom  love love love you guys and Riot! Your community was SUPER helpful and responsive during the extremely high stress build of this project. It was and is greatly appreciated. I know there are more Honda projects under development using Riot. As for me, I moved on to other things...looks like there might be something even bigger coming up that Riot is a perfect fit for. Fingers crossed and stay tuned!

**Pull request merged**
