### PR TITLE
Add bits-ui project

### PR DESCRIPTION
**Pull request by nitipit**
Hi. I've used Riot.js for quite some time and decide to create UI Library on Riot.js.
It's still new but would like to share this to Riot.js Community :)

### CODE REVIEW

**Comment by k-kuwahara** [comment]
@nitipit 

Thank you for PR! But there are some people who sent PR before you, so conflicts are occurring. Sorry, but please fix the conflict. 🙇

**Comment by nitipit** [comment]
@k-kuwahara 
Hope this should do.

**Comment by k-kuwahara** [comment]
thanks a lot!!

**Comment by k-kuwahara** [comment]
Deployment completed 👍

**Pull request merged**
